module.exports = {
  conf: {
    aliases: ["botLog", "logs"],
    name: "log",
    owner: true,
    usage: 'log [kur]',
    description: 'Botun log kanallarını kurarsınız.',
  },

 run: async ({client, msg, args, author, GeneralDatabase, SetupDatabase, MessageEmbed}) => {

   const res = await SetupDatabase.findOne({guildID: msg.guild.id})
   let manRoles = res && res.manRoles ? res.manRoles : [] 
   let ladyRoles = res && res.ladyRoles ? res.ladyRoles : [] 
   let unregisterRoles = res && res.unregisterRoles ? res.unregisterRoles : [] 
   let punitiveRole = res && res.punitiveRole ? res.punitiveRole : ""
   let bannedTagRole = res && res.bannedTagRole ? res.bannedTagRole : ""
   
   if (args[0]) {
   if (args[0] === "kur" || args[0] === "Kur" || args[0] === "KUR") {
   let message = await msg.channel.send(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM"))
   msg.guild.channels.create("Ceza Bilgi", { type: "category" }).then(async(cezaLogsCategory) => {
    await msg.guild.channels.create("ban-bilgi", { type: "text" }).then(async(banLog) => {
     await banLog.setParent(cezaLogsCategory.id)
     client.checkChannelPerms("array", manRoles, banLog.id, true) 
     client.checkChannelPerms("array", ladyRoles, banLog.id, true) 
     client.checkChannelPerms("array", unregisterRoles, banLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, banLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, banLog.id, false) 
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { banLog: banLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
   })
   await msg.guild.channels.create("jail-bilgi", { type: "text" }).then(async(jailLog) => {
    await jailLog.setParent(cezaLogsCategory.id)
    client.checkChannelPerms("array", manRoles, jailLog.id, true) 
    client.checkChannelPerms("array", ladyRoles, jailLog.id, true) 
    client.checkChannelPerms("array", unregisterRoles, jailLog.id, false) 
    client.checkChannelPerms("string", punitiveRole, jailLog.id, false) 
    client.checkChannelPerms("string", bannedTagRole, jailLog.id, false)
    await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { jailLog: jailLog.id } }, { upsert: true })
    await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
   })
   await msg.guild.channels.create("chat-mute-bilgi", { type: "text" }).then(async(chatMuteLog) => {
    await chatMuteLog.setParent(cezaLogsCategory.id)
    client.checkChannelPerms("array", manRoles, chatMuteLog.id, true) 
    client.checkChannelPerms("array", ladyRoles, chatMuteLog.id, true) 
    client.checkChannelPerms("array", unregisterRoles, chatMuteLog.id, false) 
    client.checkChannelPerms("string", punitiveRole, chatMuteLog.id, false) 
    client.checkChannelPerms("string", bannedTagRole, chatMuteLog.id, false)
    await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { chatMuteLog: chatMuteLog.id } }, { upsert: true })
    await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
   })
   await msg.guild.channels.create("voice-mute-bilgi", { type: "text" }).then(async(voiceMuteLog) => {
    await voiceMuteLog.setParent(cezaLogsCategory.id)
    client.checkChannelPerms("array", manRoles, voiceMuteLog.id, true) 
    client.checkChannelPerms("array", ladyRoles, voiceMuteLog.id, true) 
    client.checkChannelPerms("array", unregisterRoles, voiceMuteLog.id, false) 
    client.checkChannelPerms("string", punitiveRole, voiceMuteLog.id, false) 
    client.checkChannelPerms("string", bannedTagRole, voiceMuteLog.id, false)
    await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { voiceMuteLog: voiceMuteLog.id } }, { upsert: true })
    await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
   })
   await msg.guild.channels.create("ceza-puan-bilgi", { type: "text" }).then(async(cezaPuanLog) => {
    await cezaPuanLog.setParent(cezaLogsCategory.id)
    client.checkChannelPerms("array", manRoles, cezaPuanLog.id, true) 
    client.checkChannelPerms("array", ladyRoles, cezaPuanLog.id, true) 
    client.checkChannelPerms("array", unregisterRoles, cezaPuanLog.id, false) 
    client.checkChannelPerms("string", punitiveRole, cezaPuanLog.id, false) 
    client.checkChannelPerms("string", bannedTagRole, cezaPuanLog.id, false)
    await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { cezaPuanıLog: cezaPuanLog.id } }, { upsert: true })
    await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
   })
   })
   await msg.guild.channels.create("Bot Log's", { type: "category" }).then(async(botLogsCategory) => {
   await msg.guild.channels.create("tag-log", { type: "text" }).then(async(tagLog) => {
     await tagLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, tagLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, tagLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, tagLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, tagLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, tagLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { tagLog: tagLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })  
    await msg.guild.channels.create("message-log", { type: "text" }).then(async(messageLog) => {
     await messageLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, messageLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, messageLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, messageLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, messageLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, messageLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { messageLog: messageLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`6.\` Mesaj Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })  
    await msg.guild.channels.create("voice-log", { type: "text" }).then(async(voiceLog) => {
     await voiceLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, voiceLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, voiceLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, voiceLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, voiceLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, voiceLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { voiceLog: voiceLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("rol-log", { type: "text" }).then(async(rolLog) => {
     await rolLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, rolLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, rolLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, rolLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, rolLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, rolLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { rolLog: rolLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("command-log", { type: "text" }).then(async(commandLog) => {
     await commandLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, commandLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, commandLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, commandLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, commandLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, commandLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { commandsLog: commandLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("join-leave-log", { type: "text" }).then(async(joinLeaveLog) => {
     await joinLeaveLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, joinLeaveLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, joinLeaveLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, joinLeaveLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, joinLeaveLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, joinLeaveLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { joinLeaveLog: joinLeaveLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    msg.guild.channels.create("nickname-log", { type: "text" }).then(async(nicknameLog) => {
     await nicknameLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, nicknameLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, nicknameLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, nicknameLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, nicknameLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, nicknameLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { nickNameLog: nicknameLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    msg.guild.channels.create("yasaklı-tag-log", { type: "text" }).then(async(bannedTagLog) => {
     await bannedTagLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, bannedTagLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, bannedTagLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, bannedTagLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, bannedTagLog.id, false)
     client.checkChannelPerms("string", bannedTagRole, bannedTagLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { bannedTagLog: bannedTagLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    }) 
    msg.guild.channels.create("authority-left-log", { type: "text" }).then(async(authorityLeftLog) => {
     await authorityLeftLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, authorityLeftLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, authorityLeftLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, authorityLeftLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, authorityLeftLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, authorityLeftLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { AuthorityLeft: authorityLeftLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("kayıt-log", { type: "text" }).then(async(kayıtLog) => {
     await kayıtLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, kayıtLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, kayıtLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, kayıtLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, kayıtLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, kayıtLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { registerLog: kayıtLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("sıfırlama-log", { type: "text" }).then(async(sıfırlamaLog) => {
     await sıfırlamaLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, sıfırlamaLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, sıfırlamaLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, sıfırlamaLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, sıfırlamaLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, sıfırlamaLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { veriResetLog: sıfırlamaLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("streamer-cezalı-log", { type: "text" }).then(async(streamerCezalıLog) => {
     await streamerCezalıLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, streamerCezalıLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, streamerCezalıLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, streamerCezalıLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, streamerCezalıLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, streamerCezalıLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { streamerCezalıLog: streamerCezalıLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("streamer-denetim-log", { type: "text" }).then(async(streamerDenetimLog) => {
     await streamerDenetimLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, streamerDenetimLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, streamerDenetimLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, streamerDenetimLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, streamerDenetimLog.id, false)
     client.checkChannelPerms("string", bannedTagRole, streamerDenetimLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { streamerDenetim: streamerDenetimLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log\n\`18.\` Streamer Denetim Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("new-acc-log", { type: "text" }).then(async(newAccLog) => {
     await newAccLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, newAccLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, newAccLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, newAccLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, newAccLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, newAccLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { newAccLog: newAccLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log\n\`18.\` Streamer Denetim Log\n\`19.\` New Acc Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("invite-log", { type: "text" }).then(async(inviteLog) => {
     await inviteLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, inviteLog.id, true) 
     client.checkChannelPerms("array", ladyRoles, inviteLog.id, true) 
     client.checkChannelPerms("array", unregisterRoles, inviteLog.id, true) 
     client.checkChannelPerms("string", punitiveRole, inviteLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, inviteLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { inviteLog: inviteLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log\n\`18.\` Streamer Denetim Log\n\`19.\` New Acc Log\n\`20.\` Invite Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("seviye-log", { type: "text" }).then(async(levelLog) => {
     await levelLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, levelLog.id, true) 
     client.checkChannelPerms("array", ladyRoles, levelLog.id, true) 
     client.checkChannelPerms("array", unregisterRoles, levelLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, levelLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, levelLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { levelLog: levelLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log\n\`18.\` Streamer Denetim Log\n\`19.\` New Acc Log\n\`20.\` Invite Log\n\`21.\` Seviye Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })
    await msg.guild.channels.create("yetki-up-log", { type: "text" }).then(async(yetkiUpLog) => {
     await yetkiUpLog.setParent(botLogsCategory.id)
     client.checkChannelPerms("array", manRoles, yetkiUpLog.id, true) 
     client.checkChannelPerms("array", ladyRoles, yetkiUpLog.id, true) 
     client.checkChannelPerms("array", unregisterRoles, yetkiUpLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, yetkiUpLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, yetkiUpLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { yetkiUpLog: yetkiUpLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log\n\`18.\` Streamer Denetim Log\n\`19.\` New Acc Log\n\`20.\` Invite Log\n\`21.\` Seviye Log\n\`22.\` Yetki Atlama Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })})
   msg.guild.channels.create("Guard Log's", { type: "category" }).then(async(guardLogsCategory) => {
    await msg.guild.channels.create("chat-guard-log", { type: "text" }).then(async(chatGuardLog) => {
     await chatGuardLog.setParent(guardLogsCategory.id)
     client.checkChannelPerms("array", manRoles, chatGuardLog.id, false) 
     client.checkChannelPerms("array", ladyRoles, chatGuardLog.id, false) 
     client.checkChannelPerms("array", unregisterRoles, chatGuardLog.id, false) 
     client.checkChannelPerms("string", punitiveRole, chatGuardLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, chatGuardLog.id, false)
     await SetupDatabase.findOneAndUpdate({ guildID: msg.guild.id }, { $set: { chatGuardLog: chatGuardLog.id } }, { upsert: true })
     await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log\n\`18.\` Streamer Denetim Log\n\`19.\` New Acc Log\n\`20.\` Invite Log\n\`21.\` Seviye Log\n\`22.\` Yetki Atlama Log\n\`23.\` Chat Guard Log`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM")) 
    })    
  })
   await msg.guild.channels.create("kullanıcı-panel", { type: "text" }).then(async(userPanelLog) => {
    client.checkChannelPerms("array", manRoles, userPanelLog.id, true) 
    client.checkChannelPerms("array", ladyRoles, userPanelLog.id, true) 
    client.checkChannelPerms("array", unregisterRoles, userPanelLog.id, true) 
    client.checkChannelPerms("string", punitiveRole, userPanelLog.id, false) 
     client.checkChannelPerms("string", bannedTagRole, userPanelLog.id, false)
    userPanelLog.send(`!kbbutton`).then((x) => x.delete({ timeout: 2000 })).catch(() => { })
    await message.edit(new MessageEmbed().setDescription(`Başarıyla log kanalları kurulmaya başlandı.\n\nKurulan Log Kanalları:\n\`1.\` Ban Bilgi\n\`2.\` Jail Bilgi\n\`3.\` Chat Mute Bilgi\n\`4.\` Voice Mute Bilgi\n\`5.\` Ceza Puan Bilgi\n\`6.\` Tag Log\n\`7.\` Mesaj Log\n\`8.\` Ses Log\n\`9.\` Rol Log\n\`10.\` Komut Log\n\`11.\` Giriş-Çıkış Log\n\`12.\` İsim Log\n\`13.\` Yasaklı Tag Log\n\`14.\` Yetki Saldı Log\n\`15.\` Kayıt Log\n\`16.\` Sıfırlama Log\n\`17.\` Streamer Cezalı Log\n\`18.\` Streamer Denetim Log\n\`19.\` New Acc Log\n\`20.\` Invite Log\n\`21.\` Seviye Log\n\`22.\` Yetki Atlama Log\n\`23.\` Chat Guard Log\n\`24.\` Kullanıcı Panel`).setAuthor(msg.guild.name, msg.guild.iconURL({dynamic: true})).setColor("RANDOM"))    })
  }}}}